#!/bin/sh

set -e

chmod 4755 /opt/MeePFT/main.py /opt/MeePFT/bin/MeePFT

source /tmp/session_bus_address.user
dbus-send --print-reply --dest=com.meego.core.MNotificationManager /notificationmanager com.meego.core.MNotificationManager.addNotification uint32:1000 uint32:0 string:'custom' string:'MeePFT' string:'MeePFT v0.0.1 installed successfully.' string:'' string:'/usr/share/icons/hicolor/80x80/apps/MeePFT80.png' uint32:0 > /dev/null

exit 0
