#!/bin/sh

set -e

source /tmp/session_bus_address.user

case "$1" in
    remove)
dbus-send --print-reply --dest=com.meego.core.MNotificationManager /notificationmanager com.meego.core.MNotificationManager.addNotification uint32:1000 uint32:0 string:'custom' string:'MeePFT' string:'MeePFT v0.0.1 removed successfully.' string:'' string:'' uint32:0 > /dev/null
rm -rf /opt/MeePFT  ;;

    purge) rm -rf /opt/MeePFT ;;

esac

exit 0
